//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan {
    
    
    public partial class ImpresionPPalDesarrollo {
        
        /// <summary>
        /// ImpresionIngreso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan.ImpresionIngresos ImpresionIngreso;
        
        /// <summary>
        /// ImpresionProyecciones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan.ImpresionProyeccion ImpresionProyecciones;
        
        /// <summary>
        /// ImpresionNormatividades control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan.ImpresionNormatividad ImpresionNormatividades;
        
        /// <summary>
        /// ImpresionRequerimientosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan.ImpresionRequerimientos ImpresionRequerimientosNeg;
        
        /// <summary>
        /// ImpresionProduccions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan.ImpresionProduccion ImpresionProduccions;
        
        /// <summary>
        /// ImpresionProducti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan.ImpresionProductividad ImpresionProducti;
    }
}
