//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonade.PlanDeNegocioV2.Formulacion.Controles.ImpresionPlan {
    
    
    public partial class ImpresionCostosProd {
        
        /// <summary>
        /// pnltabCostosProd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnltabCostosProd;
        
        /// <summary>
        /// Tabla_Costos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Table Tabla_Costos;
        
        /// <summary>
        /// Tabla_Proyecciones_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Table Tabla_Proyecciones_1;
        
        /// <summary>
        /// Tabla_Proyecciones_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Table Tabla_Proyecciones_2;
    }
}
