CREATE TABLE [dbo].[PagoActividad] (
    [Id_PagoActividad]          INT            IDENTITY (1, 1) NOT NULL,
    [NomPagoActividad]          VARCHAR (255)  NULL,
    [Tipo]                      INT            NULL,
    [Mes]                       INT            NULL,
    [CodPagoConcepto]           INT            NULL,
    [CodPagoBeneficiario]       INT            NULL,
    [CodPagoForma]              INT            NULL,
    [Observaciones]             VARCHAR (2500) NULL,
    [CantidadDinero]            MONEY          NULL,
    [Consecutivo]               INT            NULL,
    [CodActividad]              INT            NULL,
    [CodProyecto]               INT            NULL,
    [CodPagoActividadRechazada] INT            NULL,
    [Estado]                    INT            NULL,
    [FechaIngreso]              DATETIME       NULL,
    [FechaInterventor]          DATETIME       NULL,
    [FechaCoordinador]          DATETIME       NULL,
    [FechaRtaFA]                DATETIME       NULL,
    [TipoPago]                  INT            NULL,
    [ObservaInterventor]        VARCHAR (2500) NULL,
    [RutaArchivoZIP]            VARCHAR (255)  NULL,
    [ObservacionesFA]           TEXT           NULL,
    [codigopago]                VARCHAR (255)  NULL,
    [valorretefuente]           INT            DEFAULT (0) NULL,
    [valorreteiva]              INT            DEFAULT (0) NULL,
    [valorreteica]              INT            DEFAULT (0) NULL,
    [otrosdescuentos]           INT            DEFAULT (0) NULL,
    [valorpagado]               INT            DEFAULT (0) NULL,
    [fechapago]                 DATETIME       NULL,
    [fecharechazo]              DATETIME       NULL,
    [ObservacionCambio]         TEXT           NULL,
    [TipoIdentificacion]        INT            NULL,
    [NumIdentificacion]         VARCHAR (20)   NULL,
    [Nombre]                    VARCHAR (100)  NULL,
    [Apellido]                  VARCHAR (100)  NULL,
    [RazonSocialBeneficiario]   VARCHAR (100)  NULL,
    [NumCuenta]                 VARCHAR (20)   NULL,
    [NomBanco]                  VARCHAR (255)  NULL,
    [CodigoBanco]               INT            NULL,
    [CodigoSucursal]            INT            NULL,
    CONSTRAINT [PK_PagoActividad] PRIMARY KEY CLUSTERED ([Id_PagoActividad] ASC) WITH (FILLFACTOR = 50)
);

