CREATE TABLE [dbo].[Spot_Work1] (
    [spid]     INT              CONSTRAINT [DF_Spot_Work1_spid] DEFAULT (@@spid) NULL,
    [Int1]     INT              NULL,
    [Int2]     INT              NULL,
    [Int3]     INT              NULL,
    [Int4]     INT              NULL,
    [Dec16_3]  DECIMAL (16, 3)  NULL,
    [Char50]   VARCHAR (50)     NULL,
    [Char255]  VARCHAR (255)    NULL,
    [Time1]    DATETIME         NULL,
    [Float1]   FLOAT (53)       NULL,
    [id]       INT              IDENTITY (1, 1) NOT NULL,
    [Int5]     INT              NULL,
    [Int6]     INT              NULL,
    [Int7]     INT              NULL,
    [Int8]     INT              NULL,
    [Int9]     INT              NULL,
    [Int10]    INT              NULL,
    [Int11]    INT              NULL,
    [Int12]    INT              NULL,
    [Int13]    INT              NULL,
    [Int14]    INT              NULL,
    [Int15]    INT              NULL,
    [Int16]    INT              NULL,
    [Int17]    INT              NULL,
    [Int18]    INT              NULL,
    [Int19]    INT              NULL,
    [Int20]    INT              NULL,
    [Int21]    INT              NULL,
    [Int22]    INT              NULL,
    [Int23]    INT              NULL,
    [Int24]    INT              NULL,
    [Int25]    INT              NULL,
    [Sysname1] [sysname]        NULL,
    [Sysname2] [sysname]        NULL,
    [Sysname3] [sysname]        NULL,
    [GUID1]    UNIQUEIDENTIFIER NULL,
    [Float2]   FLOAT (53)       NULL,
    [Float3]   FLOAT (53)       NULL,
    [Time2]    DATETIME         NULL,
    [Sysname4] [sysname]        NULL,
    [Char20]   VARCHAR (20)     NULL,
    [Char20a]  VARCHAR (20)     NULL,
    [Char20b]  VARCHAR (20)     NULL,
    [Sysname5] [sysname]        NULL,
    [Char255b] VARCHAR (255)    NULL,
    [Char20d]  VARCHAR (20)     NULL,
    [Char20c]  VARCHAR (20)     NULL,
    [Float4]   FLOAT (53)       NULL,
    [Float5]   FLOAT (53)       NULL,
    [Float6]   FLOAT (53)       NULL,
    [Numeric1] NUMERIC (18)     NULL,
    [Float7]   FLOAT (53)       NULL,
    [Float8]   FLOAT (53)       NULL,
    [Float9]   FLOAT (53)       NULL,
    [Float10]  FLOAT (53)       NULL,
    [Float11]  FLOAT (53)       NULL,
    [Time3]    DATETIME         NULL,
    [Binary85] VARBINARY (85)   NULL,
    [Char1000] VARCHAR (1000)   NULL
);


GO
CREATE CLUSTERED INDEX [Spot_Work1_Spid_Idx]
    ON [dbo].[Spot_Work1]([spid] ASC, [Int1] ASC) WITH (FILLFACTOR = 50);

