CREATE TABLE [dbo].[Spot_Work_LogShippingInfo] (
    [spid]                           INT              CONSTRAINT [DF__Spot_Work___spid__4959E263] DEFAULT (@@spid) NOT NULL,
    [primary_server_name]            [sysname]        NOT NULL,
    [primary_database_name]          [sysname]        NOT NULL,
    [secondary_server_name]          [sysname]        NOT NULL,
    [secondary_database_name]        [sysname]        NOT NULL,
    [backup_threshold]               INT              NOT NULL,
    [backup_threshold_alert]         INT              NOT NULL,
    [backup_threshold_alert_enabled] BIT              NOT NULL,
    [last_backup_filename]           NVARCHAR (500)   NOT NULL,
    [last_backup_last_updated]       DATETIME         NOT NULL,
    [backup_outage_start_time]       INT              NOT NULL,
    [backup_outage_end_time]         INT              NOT NULL,
    [backup_outage_weekday_mask]     INT              NOT NULL,
    [backup_in_sync]                 INT              NULL,
    [backup_delta]                   INT              NULL,
    [last_copied_filename]           NVARCHAR (500)   NOT NULL,
    [last_copied_last_updated]       DATETIME         NOT NULL,
    [last_loaded_filename]           NVARCHAR (500)   NOT NULL,
    [last_loaded_last_updated]       DATETIME         NOT NULL,
    [copy_delta]                     INT              NULL,
    [copy_enabled]                   BIT              NOT NULL,
    [load_enabled]                   BIT              NOT NULL,
    [out_of_sync_threshold]          INT              NOT NULL,
    [load_threshold_alert]           INT              NOT NULL,
    [load_threshold_alert_enabled]   BIT              NOT NULL,
    [load_outage_start_time]         INT              NOT NULL,
    [load_outage_end_time]           INT              NOT NULL,
    [load_outage_weekday_mask]       INT              NOT NULL,
    [load_in_sync]                   INT              NULL,
    [load_delta]                     INT              NULL,
    [maintenance_plan_id]            UNIQUEIDENTIFIER NULL,
    [secondary_plan_id]              UNIQUEIDENTIFIER NOT NULL,
    [primary_server_time]            DATETIME         NULL,
    [secondary_server_time]          DATETIME         NULL,
    [monitor_server_time]            DATETIME         NULL
);

