#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Fonade")]
	public partial class FonadeDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public FonadeDatosDataContext() : 
				base(global::Datos.Properties.Settings.Default.FonadeConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public FonadeDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FonadeDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FonadeDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FonadeDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MD_ConsultarTareasPendientesXContacto")]
		public ISingleResult<MD_ConsultarTareasPendientesXContactoResult> MD_ConsultarTareasPendientesXContacto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IN_CodContacto", DbType="Int")] System.Nullable<int> iN_CodContacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IN_OffSet", DbType="Int")] System.Nullable<int> iN_OffSet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IN_RegistrosXPagina", DbType="Int")] System.Nullable<int> iN_RegistrosXPagina)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iN_CodContacto, iN_OffSet, iN_RegistrosXPagina);
			return ((ISingleResult<MD_ConsultarTareasPendientesXContactoResult>)(result.ReturnValue));
		}
	}
	
	public partial class MD_ConsultarTareasPendientesXContactoResult
	{
		
		private string _Tipo;
		
		private string _Ejecutable;
		
		private string _Icono;
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private int _CodigoTarea;
		
		private bool _RecordatorioEmail;
		
		private short _NivelUrgencia;
		
		private bool _RequiereRespuesta;
		
		private bool _RecordatorioPantalla;
		
		private int _CodigoContactoAgendo;
		
		private int _IdTareaUsuarioRepeticion;
		
		private string _Parametros;
		
		private System.DateTime _Fecha;
		
		private System.Nullable<int> _IdProyecto;
		
		private string _NombreProyecto;
		
		private string _NombreContactoAgendo;
		
		private string _ApellidoContactoAgendo;
		
		private string _Email;
		
		private int _GrupoContactoAgendo;
		
		public MD_ConsultarTareasPendientesXContactoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ejecutable", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Ejecutable
		{
			get
			{
				return this._Ejecutable;
			}
			set
			{
				if ((this._Ejecutable != value))
				{
					this._Ejecutable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icono", DbType="VarChar(100)")]
		public string Icono
		{
			get
			{
				return this._Icono;
			}
			set
			{
				if ((this._Icono != value))
				{
					this._Icono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTarea", DbType="Int NOT NULL")]
		public int CodigoTarea
		{
			get
			{
				return this._CodigoTarea;
			}
			set
			{
				if ((this._CodigoTarea != value))
				{
					this._CodigoTarea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordatorioEmail", DbType="Bit NOT NULL")]
		public bool RecordatorioEmail
		{
			get
			{
				return this._RecordatorioEmail;
			}
			set
			{
				if ((this._RecordatorioEmail != value))
				{
					this._RecordatorioEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelUrgencia", DbType="SmallInt NOT NULL")]
		public short NivelUrgencia
		{
			get
			{
				return this._NivelUrgencia;
			}
			set
			{
				if ((this._NivelUrgencia != value))
				{
					this._NivelUrgencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiereRespuesta", DbType="Bit NOT NULL")]
		public bool RequiereRespuesta
		{
			get
			{
				return this._RequiereRespuesta;
			}
			set
			{
				if ((this._RequiereRespuesta != value))
				{
					this._RequiereRespuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordatorioPantalla", DbType="Bit NOT NULL")]
		public bool RecordatorioPantalla
		{
			get
			{
				return this._RecordatorioPantalla;
			}
			set
			{
				if ((this._RecordatorioPantalla != value))
				{
					this._RecordatorioPantalla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoContactoAgendo", DbType="Int NOT NULL")]
		public int CodigoContactoAgendo
		{
			get
			{
				return this._CodigoContactoAgendo;
			}
			set
			{
				if ((this._CodigoContactoAgendo != value))
				{
					this._CodigoContactoAgendo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTareaUsuarioRepeticion", DbType="Int NOT NULL")]
		public int IdTareaUsuarioRepeticion
		{
			get
			{
				return this._IdTareaUsuarioRepeticion;
			}
			set
			{
				if ((this._IdTareaUsuarioRepeticion != value))
				{
					this._IdTareaUsuarioRepeticion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parametros", DbType="VarChar(255)")]
		public string Parametros
		{
			get
			{
				return this._Parametros;
			}
			set
			{
				if ((this._Parametros != value))
				{
					this._Parametros = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProyecto", DbType="Int")]
		public System.Nullable<int> IdProyecto
		{
			get
			{
				return this._IdProyecto;
			}
			set
			{
				if ((this._IdProyecto != value))
				{
					this._IdProyecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProyecto", DbType="VarChar(300)")]
		public string NombreProyecto
		{
			get
			{
				return this._NombreProyecto;
			}
			set
			{
				if ((this._NombreProyecto != value))
				{
					this._NombreProyecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreContactoAgendo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreContactoAgendo
		{
			get
			{
				return this._NombreContactoAgendo;
			}
			set
			{
				if ((this._NombreContactoAgendo != value))
				{
					this._NombreContactoAgendo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoContactoAgendo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ApellidoContactoAgendo
		{
			get
			{
				return this._ApellidoContactoAgendo;
			}
			set
			{
				if ((this._ApellidoContactoAgendo != value))
				{
					this._ApellidoContactoAgendo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoContactoAgendo", DbType="Int NOT NULL")]
		public int GrupoContactoAgendo
		{
			get
			{
				return this._GrupoContactoAgendo;
			}
			set
			{
				if ((this._GrupoContactoAgendo != value))
				{
					this._GrupoContactoAgendo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
