#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FonadeSE4")]
	public partial class ObservacionEvaluacionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertLOVObjetoSE(LOVObjetoSE instance);
    partial void UpdateLOVObjetoSE(LOVObjetoSE instance);
    partial void DeleteLOVObjetoSE(LOVObjetoSE instance);
    partial void InsertLOVObjetoSEAcreditacion(LOVObjetoSEAcreditacion instance);
    partial void UpdateLOVObjetoSEAcreditacion(LOVObjetoSEAcreditacion instance);
    partial void DeleteLOVObjetoSEAcreditacion(LOVObjetoSEAcreditacion instance);
    #endregion
		
		public ObservacionEvaluacionDataContext() : 
				base(global::Datos.Properties.Settings.Default.FonadeSE4ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ObservacionEvaluacionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ObservacionEvaluacionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ObservacionEvaluacionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ObservacionEvaluacionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOVObjetoSE> LOVObjetoSEs
		{
			get
			{
				return this.GetTable<LOVObjetoSE>();
			}
		}
		
		public System.Data.Linq.Table<LOVObjetoSEAcreditacion> LOVObjetoSEAcreditacion
		{
			get
			{
				return this.GetTable<LOVObjetoSEAcreditacion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOVObjetoSE")]
	public partial class LOVObjetoSE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_LovObjetoSE;
		
		private string _NomLovObjetoSE;
		
		private string _Descripcion;
		
		private string _Valor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_LovObjetoSEChanging(int value);
    partial void OnId_LovObjetoSEChanged();
    partial void OnNomLovObjetoSEChanging(string value);
    partial void OnNomLovObjetoSEChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    #endregion
		
		public LOVObjetoSE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_LovObjetoSE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_LovObjetoSE
		{
			get
			{
				return this._Id_LovObjetoSE;
			}
			set
			{
				if ((this._Id_LovObjetoSE != value))
				{
					this.OnId_LovObjetoSEChanging(value);
					this.SendPropertyChanging();
					this._Id_LovObjetoSE = value;
					this.SendPropertyChanged("Id_LovObjetoSE");
					this.OnId_LovObjetoSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomLovObjetoSE", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string NomLovObjetoSE
		{
			get
			{
				return this._NomLovObjetoSE;
			}
			set
			{
				if ((this._NomLovObjetoSE != value))
				{
					this.OnNomLovObjetoSEChanging(value);
					this.SendPropertyChanging();
					this._NomLovObjetoSE = value;
					this.SendPropertyChanged("NomLovObjetoSE");
					this.OnNomLovObjetoSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(255)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOVObjetoSEAcreditacion")]
	public partial class LOVObjetoSEAcreditacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_LovObjetoSEAcreditacion;
		
		private string _NomLovObjetoSE;
		
		private string _Descripcion;
		
		private string _Valor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_LovObjetoSEAcreditacionChanging(int value);
    partial void OnId_LovObjetoSEAcreditacionChanged();
    partial void OnNomLovObjetoSEChanging(string value);
    partial void OnNomLovObjetoSEChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    #endregion
		
		public LOVObjetoSEAcreditacion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_LovObjetoSEAcreditacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_LovObjetoSEAcreditacion
		{
			get
			{
				return this._Id_LovObjetoSEAcreditacion;
			}
			set
			{
				if ((this._Id_LovObjetoSEAcreditacion != value))
				{
					this.OnId_LovObjetoSEAcreditacionChanging(value);
					this.SendPropertyChanging();
					this._Id_LovObjetoSEAcreditacion = value;
					this.SendPropertyChanged("Id_LovObjetoSEAcreditacion");
					this.OnId_LovObjetoSEAcreditacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomLovObjetoSE", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string NomLovObjetoSE
		{
			get
			{
				return this._NomLovObjetoSE;
			}
			set
			{
				if ((this._NomLovObjetoSE != value))
				{
					this.OnNomLovObjetoSEChanging(value);
					this.SendPropertyChanging();
					this._NomLovObjetoSE = value;
					this.SendPropertyChanged("NomLovObjetoSE");
					this.OnNomLovObjetoSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(255)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
