-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[MD_ConcultarInfoAcreditacion]
	-- Add the parameters for the stored procedure here
	@Accion varchar(50),
	@Codproyecto int,
	@CodConvocatoria int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	if @Accion = 'RsProyecto'
		begin
			SELECT P.NOMPROYECTO,C.NOMCIUDAD,D.NOMDEPARTAMENTO, I.NOMINSTITUCION,I.NOMUNIDAD FROM PROYECTO P
			JOIN CIUDAD C ON (C.ID_CIUDAD = P.CODCIUDAD)
			JOIN DEPARTAMENTO D ON (D.ID_DEPARTAMENTO = C.CODDEPARTAMENTO)
			JOIN INSTITUCION I ON (P.CODINSTITUCION= I.ID_INSTITUCION)
			WHERE P.ID_PROYECTO = @Codproyecto
		end
	if @Accion = 'Rsacreditacio'
		begin
			SELECT PAD.ID_PROYECTOACREDITACIONDOCUMENTO,PAD.CODCONTACTO,C.NOMBRES + ' ' + C.APELLIDOS 'NOMBRE',PAD.PENDIENTE,PAD.FECHAPENDIENTE,PAD.OBSERVACIONPENDIENTE,PAD.ASUNTOPENDIENTE,
			PAD.SUBSANADO,PAD.OBSERVACIONSUBSANADO,PAD.ASUNTOSUBSANADO,PAD.FECHASUBSANADO,PAD.ACREDITADO,PAD.OBSERVACIONACREDITADO,PAD.ASUNTOACREDITADO,PAD.FECHAACREDITADO,
			PAD.NOACREDITADO,PAD.OBSERVACIONNOACREDITADO,PAD.ASUNTONOACREDITADO,PAD.FECHANOACREDITADO,PAD.FLAGANEXO1,PAD.FLAGANEXO2,PAD.FLAGANEXO3,PAD.FLAGDI,
			PAD.FLAGCERTIFICACIONES,PAD.FLAGDIPLOMA,PAD.FLAGACTA FROM PROYECTOACREDITACIONDOCUMENTO PAD JOIN CONTACTO C ON (PAD.CODCONTACTO = C.ID_CONTACTO) WHERE PAD.CODPROYECTO= @Codproyecto AND PAD.CODCONVOCATORIA= @CodConvocatoria
		END
end