-- =============================================
-- Author:		Alberto palencia Benedetti
-- Create date: 24/03/2014
-- Description:	se obtiene los planes acreditados por el usuario
-- ejemplo 
-- MD_PlanesAcreditarUsuario 81258
-- =============================================
CREATE PROCEDURE MD_PlanesAcreditarUsuario
	-- Add the parameters for the stored procedure here
	@idusuario int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON

SELECT 
	DISTINCT P.ID_PROYECTO
	,P.NOMPROYECTO
	,PC.FECHAINICIO 'FECHAASIGNACION'
	,DATEDIFF(DD,PC.FECHAINICIO,GETDATE()) 'DIAS'
	,MAX(PC.CODCONVOCATORIA) 'CODCONVOCATORIA'
	,E.NOMESTADO 'ESTADO'
FROM PROYECTO P JOIN PROYECTOCONTACTO PC ON (PC.INACTIVO=0 AND PC.CODPROYECTO=P.ID_PROYECTO 
AND P.CODESTADO IN (10,11,12,13,14,15,16)) JOIN ESTADO E ON (E.ID_ESTADO = P.CODESTADO) 
INNER JOIN (SELECT DISTINCT P.ID_PROYECTO, MAX(PC.CODCONVOCATORIA) 'CODCONVOCATORIA'
FROM PROYECTO P JOIN PROYECTOCONTACTO PC ON (PC.INACTIVO=0 AND PC.CODPROYECTO=P.ID_PROYECTO AND P.CODESTADO IN (10,11,12,13,14,15,16)) 
JOIN ESTADO E ON (E.ID_ESTADO = P.CODESTADO)
WHERE PC.ACREDITADOR = 1
AND PC.CODCONVOCATORIA IS NOT NULL AND PC.CODCONTACTO =  @idusuario
GROUP BY P.ID_PROYECTO) t on (t.ID_PROYECTO=p.ID_PROYECTO and t.CODCONVOCATORIA=pc.CODCONVOCATORIA)
WHERE PC.ACREDITADOR = 1 AND PC.CODCONVOCATORIA IS NOT NULL AND PC.CODCONTACTO = @idusuario
GROUP BY P.ID_PROYECTO,P.NOMPROYECTO,PC.FECHAINICIO,E.NOMESTADO

END